/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.PessoaJuridicaDAO;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Model.PessoaJuridica;

/**
 *
 * @author jefer
 */
public class PessoaJuridicaView extends javax.swing.JFrame {

    /**
     * Creates new form MenuView
     */
    public static PessoaJuridicaView telaUnica;
    private PessoaJuridicaDAO pessoaJuridicaTela;
    public PessoaJuridicaView() {
        pessoaJuridicaTela = new PessoaJuridicaDAO();
        if (pessoaJuridicaTela.CriaConexao()) {
            initComponents();
            addInTable();
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao criar a conexão com o banco de dados.", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public static PessoaJuridicaView getTela(){
        if(telaUnica == null){
            telaUnica = new PessoaJuridicaView();

        }
        return telaUnica;
    }
    
    public void voltar(){
        int resp = JOptionPane.showConfirmDialog(
                    null,
                    "Deseja Voltar?",
                    "Saida",
                    JOptionPane.YES_NO_OPTION
                );
        if(resp == 0){
            dispose();
        }
    }
    
    public void addInTable(){
        
        DefaultTableModel modelo = (DefaultTableModel) tbPessoaJuridica.getModel();
        int aux = 0;
        modelo.setRowCount(aux);
        for(PessoaJuridica pessoaJuridica : pessoaJuridicaTela.getTodasPessoasJuridica()){
            modelo.insertRow(aux, new Object []{pessoaJuridica.getNome(), pessoaJuridica.getCnpj(),pessoaJuridica.getTelefone(),pessoaJuridica.getEndereco()});
            aux++;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbPessoaJuridica = new javax.swing.JTable();
        jButtonVoltar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButtonAdicionar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jTextFieldCnpj = new javax.swing.JTextField();
        jTextFieldTelefone = new javax.swing.JTextField();
        jTextFieldEndereco = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButtonConsultar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldConsulta = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbPessoaJuridica.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome", "Cnpj", "Telefone", "Endereço"
            }
        ));
        jScrollPane1.setViewportView(tbPessoaJuridica);

        jButtonVoltar.setText("Voltar");
        jButtonVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonVoltarMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Pessoas Juridicas");

        jButtonAdicionar.setText("Adicionar");
        jButtonAdicionar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAdicionarMouseClicked(evt);
            }
        });

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonExcluirMouseClicked(evt);
            }
        });

        jButtonEditar.setText("Editar");
        jButtonEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonEditarMouseClicked(evt);
            }
        });

        jLabel2.setText("Nome :");

        jLabel3.setText("Cnpj :");

        jLabel4.setText("Endereço :");

        jLabel5.setText("Telefone :");

        jLabel6.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        jLabel6.setText("Edição, exclusão e consulta são feitas a partir do Cnpj");

        jButtonConsultar.setText("Consultar");
        jButtonConsultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonConsultarMouseClicked(evt);
            }
        });

        jLabel7.setText("Consulta :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButtonVoltar)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 825, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldConsulta))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonAdicionar)
                                .addGap(138, 138, 138)
                                .addComponent(jButtonConsultar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jTextFieldCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(170, 170, 170)
                                .addComponent(jButtonEditar)
                                .addGap(133, 133, 133)
                                .addComponent(jButtonExcluir)))))
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(352, 352, 352))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(286, 286, 286))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAdicionar)
                    .addComponent(jButtonExcluir)
                    .addComponent(jButtonEditar)
                    .addComponent(jButtonConsultar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jButtonVoltar)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonVoltarMouseClicked
        voltar();
    }//GEN-LAST:event_jButtonVoltarMouseClicked

    private void jButtonAdicionarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAdicionarMouseClicked
       PessoaJuridica pessoaJuridica = new PessoaJuridica();
        pessoaJuridica.setNome(jTextFieldNome.getText());
        pessoaJuridica.setCnpj(jTextFieldCnpj.getText());
        pessoaJuridica.setTelefone(jTextFieldTelefone.getText());
        pessoaJuridica.setEndereco(jTextFieldEndereco.getText());
        
        if(pessoaJuridicaTela.savePessoaJuridica(pessoaJuridica)){
            JOptionPane.showMessageDialog(null, "Pessoa Juridica cadastrada com sucesso", "SUCESSO", JOptionPane.DEFAULT_OPTION);
            addInTable();
        } else {
            JOptionPane.showMessageDialog(null, "Pessoa Juridica com CNPJ já cadastrado", "ERRO", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonAdicionarMouseClicked

    private void jButtonExcluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonExcluirMouseClicked
        if(pessoaJuridicaTela.deletePessoaJuridica(jTextFieldCnpj.getText())){
            JOptionPane.showMessageDialog(null, "Pessoa Juridica deletada com sucesso", "SUCESSO", JOptionPane.DEFAULT_OPTION);
            addInTable();
        } else {
            JOptionPane.showMessageDialog(null, "Erro ao deletar Pessoa Juridica", "ERRO", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonExcluirMouseClicked

    private void jButtonEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonEditarMouseClicked
        PessoaJuridica pessoaJuridica = new PessoaJuridica();
        pessoaJuridica.setNome(jTextFieldNome.getText());
        pessoaJuridica.setCnpj(jTextFieldCnpj.getText());
        pessoaJuridica.setTelefone(jTextFieldTelefone.getText());
        pessoaJuridica.setEndereco(jTextFieldEndereco.getText());
        
        if(pessoaJuridicaTela.updatePessoaJuridica(pessoaJuridica)){
            JOptionPane.showMessageDialog(null, "Pessoa Juridica atualizada com sucesso", "SUCESSO", JOptionPane.DEFAULT_OPTION);
            addInTable();
        } else {
            JOptionPane.showMessageDialog(null, "Erro ao atualizar Pessoa Juridica", "ERRO", JOptionPane.ERROR_MESSAGE); 
        }
    }//GEN-LAST:event_jButtonEditarMouseClicked

    private void jButtonConsultarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonConsultarMouseClicked
    String cnpj = jTextFieldConsulta.getText().trim();

        if (cnpj.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, digite um CNPJ válido.", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }

        PessoaJuridica pessoaJuridicaConsultada = pessoaJuridicaTela.getPessoaJuridica(cnpj);

        if (pessoaJuridicaConsultada != null) {
            JOptionPane.showMessageDialog(this, "Pessoa Juridica encontrada:\nCNPJ: " + pessoaJuridicaConsultada.getCnpj() + "\nNome: " + pessoaJuridicaConsultada.getNome() + "\nTelefone: " + pessoaJuridicaConsultada.getTelefone() + "\nEndereco: " + pessoaJuridicaConsultada.getEndereco(), "Consulta de Pessoa Juridica", JOptionPane.INFORMATION_MESSAGE);

            jTextFieldCnpj.setText(pessoaJuridicaConsultada.getCnpj());
            jTextFieldNome.setText(pessoaJuridicaConsultada.getNome());
            jTextFieldTelefone.setText(pessoaJuridicaConsultada.getTelefone());
            jTextFieldEndereco.setText(pessoaJuridicaConsultada.getEndereco());
        } else {
            JOptionPane.showMessageDialog(this, "Pessoa Juridica com o CNPJ " + cnpj + " não encontrada.", "Erro", JOptionPane.ERROR_MESSAGE);

            jTextFieldCnpj.setText("");
            jTextFieldNome.setText("");
            jTextFieldTelefone.setText("");
            jTextFieldEndereco.setText("");
        }
    }//GEN-LAST:event_jButtonConsultarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PessoaJuridicaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PessoaJuridicaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PessoaJuridicaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PessoaJuridicaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PessoaJuridicaView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdicionar;
    private javax.swing.JButton jButtonConsultar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldCnpj;
    private javax.swing.JTextField jTextFieldConsulta;
    private javax.swing.JTextField jTextFieldEndereco;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldTelefone;
    private javax.swing.JTable tbPessoaJuridica;
    // End of variables declaration//GEN-END:variables
}
